version: "3"
services:
  gses2-app:
    build:
      context: .
      dockerfile: ./build/package/Dockerfile
    volumes:
      - storage_volume:/app/storage/
    ports:
      - "8080:8080"
      - "465:465"
    env_file:
      - .env
    restart: on-failure

volumes:
  storage_volume:
