name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Docker Compose Up
      run: docker-compose -f docker-compose.e2e.yml up -d

    - name: Install Newman
      run: sudo npm install -g newman

    - name: Run E2E Tests
      run: |
        sleep 120
        newman run ./test/E2E/postman/tests.e2e.json

    - name: Docker Compose Down
      if: always()
      run: docker-compose -f docker-compose.e2e.yml down
