name: Mutation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install go-mutesting
        run: go install github.com/zimmski/go-mutesting/cmd/go-mutesting@latest

      - name: Run Mutation Tests
        run: |
          output=$(go-mutesting ./...);
          mutation_score=$(echo "$output" | awk '/The mutation score is/{print $5}');
          threshold=0.3;
          if (( $(echo "$mutation_score > $threshold" | bc -l) )); then
            echo "Test is complete. Mutation score ($mutation_score) is higher than $threshold.";
          else
            echo "Test is incomplete. Mutation score ($mutation_score) is not higher than $threshold.";
            exit 1; # Fail the job if the score is not higher than the threshold
          fi
